/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description Upload de TXT/Markdown/PDF (multipart `file`) ou texto colado (campo `text`).
         */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Text Source */
        post: operations["create_text_source_api_v1_sources_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Run
         * @description Exclui uma execucao encerrada e todos os seus registros (eventos, artefatos, chamadas, orcamento).
         */
        delete: operations["delete_run_api_v1_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Idempotente: bloqueia novas chamadas; chamadas em voo terminam e so atualizam uso/artefatos.
         */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Run
         * @description Nova tentativa explicita: novo run_id vinculado ao anterior, com a mesma configuracao congelada.
         */
        post: operations["retry_run_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine Run
         * @description Rodada de melhoria: as equipes escolhidas revisam com o feedback do cliente; todas sao reavaliadas.
         */
        post: operations["refine_run_api_v1_runs__run_id__refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/action-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Plan Run
         * @description Entrega final: a equipe escolhida (padrao: vencedora) transforma a proposta em plano de acao.
         */
        post: operations["action_plan_run_api_v1_runs__run_id__action_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Report */
        get: operations["run_report_api_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events List */
        get: operations["events_list_api_v1_runs__run_id__events_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events Sse
         * @description SSE com IDs sequenciais. Reconexao via Last-Event-ID (ou ?after=). Transmite apenas estado/resultados publicos.
         */
        get: operations["events_sse_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Prepare
         * @description Cria as fontes SINTETICAS do cenario de demonstracao para o proprietario e devolve a configuracao pronta.
         */
        post: operations["demo_prepare_api_v1_demo_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionKpi */
        ActionKpi: {
            /** Metric */
            metric: string;
            /** Target */
            target: string;
        };
        /** ActionPhase */
        ActionPhase: {
            /** Name */
            name: string;
            /**
             * Duration
             * @default
             */
            duration: string;
            /**
             * Goal
             * @default
             */
            goal: string;
            /** Tasks */
            tasks: components["schemas"]["ActionTask"][];
        };
        /** ActionPlan */
        ActionPlan: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Objectives */
            objectives: string[];
            /** Phases */
            phases: components["schemas"]["ActionPhase"][];
            /** Kpis */
            kpis: components["schemas"]["ActionKpi"][];
            /** Risks */
            risks: components["schemas"]["ActionRisk"][];
            /**
             * Budget Estimate
             * @default
             */
            budget_estimate: string;
            /** Next Steps */
            next_steps: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Candidate Id */
            candidate_id: string;
            /** Proposal Version */
            proposal_version: number;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Detail Request
             * @description O que o cliente pediu para detalhar nesta versao.
             * @default
             */
            detail_request: string;
            /** Invalid Evidence Ids */
            invalid_evidence_ids: string[];
            /** Call Ids */
            call_ids: string[];
        };
        /** ActionPlanIn */
        ActionPlanIn: {
            /**
             * Candidate Id
             * @description Equipe que monta o plano; padrao = vencedora.
             */
            candidate_id?: string | null;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /**
         * ActionPlanSpec
         * @description Entrega final: a equipe escolhida transforma a proposta em um plano de acao concreto.
         *     Pedido sobre um plano ja pronto = nova versao mais detalhada (instructions = o que detalhar).
         */
        "ActionPlanSpec-Input": {
            /** Parent Run Id */
            parent_run_id: string;
            /** Candidate Id */
            candidate_id: string;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /**
         * ActionPlanSpec
         * @description Entrega final: a equipe escolhida transforma a proposta em um plano de acao concreto.
         *     Pedido sobre um plano ja pronto = nova versao mais detalhada (instructions = o que detalhar).
         */
        "ActionPlanSpec-Output": {
            /** Parent Run Id */
            parent_run_id: string;
            /** Candidate Id */
            candidate_id: string;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /** ActionRisk */
        ActionRisk: {
            /** Risk */
            risk: string;
            /** Mitigation */
            mitigation: string;
        };
        /** ActionTask */
        ActionTask: {
            /** Task */
            task: string;
            /**
             * Owner
             * @default
             */
            owner: string;
            /**
             * Deliverable
             * @default
             */
            deliverable: string;
        };
        /** Body_create_source_api_v1_sources_post */
        Body_create_source_api_v1_sources_post: {
            /** File */
            file?: string | null;
            /** Text */
            text?: string | null;
            /** Title */
            title?: string | null;
        };
        /** BudgetBucketView */
        BudgetBucketView: {
            /** Bucket Key */
            bucket_key: string;
            /** Cap */
            cap: string | null;
            /** Spent */
            spent: string;
            /** Reserved */
            reserved: string;
            /** Provisioned */
            provisioned: string;
            /** Pending Unknown */
            pending_unknown: string;
            /** Calls Used */
            calls_used: number;
            /** Calls Provisioned */
            calls_provisioned: number;
        };
        /** BudgetConfig */
        "BudgetConfig-Input": {
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Total Cap
             * @description Teto monetario. Obrigatorio em modo real.
             */
            total_cap?: number | string | null;
            /**
             * Strict
             * @description Teto estrito (bloqueia chamadas sem cobertura) ou indicativo.
             * @default true
             */
            strict: boolean;
            /**
             * Common Share Pct
             * @description Percentual do teto para a cota comum (evidencias + Judge).
             * @default 30
             */
            common_share_pct: number | string;
            /**
             * Max Total Calls
             * @default 32
             */
            max_total_calls: number;
            /**
             * Max Concurrent Calls
             * @default 2
             */
            max_concurrent_calls: number;
            /**
             * Run Deadline S
             * @default 300
             */
            run_deadline_s: number;
            /**
             * Call Timeout S
             * @default 60
             */
            call_timeout_s: number;
            /**
             * Max Attempts Per Call
             * @default 2
             */
            max_attempts_per_call: number;
        };
        /** BudgetConfig */
        "BudgetConfig-Output": {
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Total Cap
             * @description Teto monetario. Obrigatorio em modo real.
             */
            total_cap: string | null;
            /**
             * Strict
             * @description Teto estrito (bloqueia chamadas sem cobertura) ou indicativo.
             * @default true
             */
            strict: boolean;
            /**
             * Common Share Pct
             * @description Percentual do teto para a cota comum (evidencias + Judge).
             * @default 30
             */
            common_share_pct: string;
            /**
             * Max Total Calls
             * @default 32
             */
            max_total_calls: number;
            /**
             * Max Concurrent Calls
             * @default 2
             */
            max_concurrent_calls: number;
            /**
             * Run Deadline S
             * @default 300
             */
            run_deadline_s: number;
            /**
             * Call Timeout S
             * @default 60
             */
            call_timeout_s: number;
            /**
             * Max Attempts Per Call
             * @default 2
             */
            max_attempts_per_call: number;
        };
        /** CandidateConfig */
        "CandidateConfig-Input": {
            /**
             * Candidate Id
             * @description Gerado pelo servidor (c1..c4) se ausente.
             */
            candidate_id?: string | null;
            /** Name */
            name: string;
            /** Preset */
            preset?: ("balanced" | "cost" | "robust" | "explorer") | null;
            /**
             * Instructions
             * @description Instrucoes estrategicas privadas do pensante.
             * @default
             */
            instructions: string;
            /** @default mock */
            provider: components["schemas"]["Provider"];
            /**
             * Model Option
             * @description Modelo principal (planejar, propor, revisar).
             * @default mock-default
             */
            model_option: string;
            /**
             * Secondary Model Option
             * @description Modelo economico opcional (mesmo provedor) para tarefas internas simples.
             */
            secondary_model_option?: string | null;
            /**
             * Secondary For
             * @description Onde o modelo economico e usado por padrao.
             */
            secondary_for?: ("research" | "critique")[];
            /** Allowed Specialists */
            allowed_specialists?: components["schemas"]["SpecialistKind"][];
            /**
             * Max Specialist Tasks
             * @default 2
             */
            max_specialist_tasks: number;
            /**
             * Max Output Tokens
             * @default 2000
             */
            max_output_tokens: number;
            /**
             * Quota Weight
             * @description Peso relativo da cota; default igual.
             * @default 1
             */
            quota_weight: number | string;
            /** Color */
            color?: string | null;
        };
        /** CandidateConfig */
        "CandidateConfig-Output": {
            /**
             * Candidate Id
             * @description Gerado pelo servidor (c1..c4) se ausente.
             */
            candidate_id: string | null;
            /** Name */
            name: string;
            /** Preset */
            preset: ("balanced" | "cost" | "robust" | "explorer") | null;
            /**
             * Instructions
             * @description Instrucoes estrategicas privadas do pensante.
             * @default
             */
            instructions: string;
            /** @default mock */
            provider: components["schemas"]["Provider"];
            /**
             * Model Option
             * @description Modelo principal (planejar, propor, revisar).
             * @default mock-default
             */
            model_option: string;
            /**
             * Secondary Model Option
             * @description Modelo economico opcional (mesmo provedor) para tarefas internas simples.
             */
            secondary_model_option: string | null;
            /**
             * Secondary For
             * @description Onde o modelo economico e usado por padrao.
             */
            secondary_for: ("research" | "critique")[];
            /** Allowed Specialists */
            allowed_specialists: components["schemas"]["SpecialistKind"][];
            /**
             * Max Specialist Tasks
             * @default 2
             */
            max_specialist_tasks: number;
            /**
             * Max Output Tokens
             * @default 2000
             */
            max_output_tokens: number;
            /**
             * Quota Weight
             * @description Peso relativo da cota; default igual.
             * @default 1
             */
            quota_weight: string;
            /** Color */
            color: string | null;
        };
        /** CatalogJudgePersona */
        CatalogJudgePersona: {
            /** Persona */
            persona: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Instructions */
            instructions: string;
            /** Rubric */
            rubric: {
                [key: string]: unknown;
            };
        };
        /** CatalogModelOption */
        CatalogModelOption: {
            provider: components["schemas"]["Provider"];
            /** Option */
            option: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @description 'fixed_model' ou 'routing_capability'
             */
            kind: string;
            /** Capabilities */
            capabilities: string[];
            /** Max Context Tokens */
            max_context_tokens: number | null;
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Supports Json Mode */
            supports_json_mode: boolean;
            /** Price Input Per 1M */
            price_input_per_1m: string | null;
            /** Price Output Per 1M */
            price_output_per_1m: string | null;
            /** Price Version */
            price_version: string;
            /** Price Known */
            price_known: boolean;
            /** Enabled */
            enabled: boolean;
            /** Unavailable Reason */
            unavailable_reason: string | null;
        };
        /** CatalogPreset */
        CatalogPreset: {
            /** Preset */
            preset: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Instructions */
            instructions: string;
            /** Model Option By Provider */
            model_option_by_provider: {
                [key: string]: string;
            };
            /** Secondary By Provider */
            secondary_by_provider: {
                [key: string]: string;
            };
            /** Allowed Specialists */
            allowed_specialists: string[];
            /** Max Specialist Tasks */
            max_specialist_tasks: number;
        };
        /** CatalogResponse */
        CatalogResponse: {
            /** App Version */
            app_version: string;
            /** Catalog Version */
            catalog_version: string;
            /** Modes */
            modes: components["schemas"]["ExecutionMode"][];
            /** Providers */
            providers: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Model Options */
            model_options: components["schemas"]["CatalogModelOption"][];
            /** Specialists */
            specialists: {
                [key: string]: unknown;
            }[];
            /** Presets */
            presets: components["schemas"]["CatalogPreset"][];
            /** Limits */
            limits: {
                [key: string]: unknown;
            };
            /** Default Rubric */
            default_rubric: {
                [key: string]: unknown;
            };
            /** Judge Personas */
            judge_personas: components["schemas"]["CatalogJudgePersona"][];
            /** Mock Scenarios */
            mock_scenarios: string[];
            /** Demo Preset Available */
            demo_preset_available: boolean;
        };
        /**
         * ChallengeConfig
         * @description Configuracao completa de um desafio. Depois de validada e resolvida vira o snapshot imutavel do Run.
         */
        "ChallengeConfig-Input": {
            /** Title */
            title?: string | null;
            /** Objective */
            objective: string;
            /**
             * Context
             * @default
             */
            context: string;
            /** Source Ids */
            source_ids?: string[];
            /** Constraints */
            constraints?: components["schemas"]["Constraint-Input"][];
            rubric?: components["schemas"]["Rubric-Input"];
            budget?: components["schemas"]["BudgetConfig-Input"];
            /** @default mock */
            mode: components["schemas"]["ExecutionMode"];
            /**
             * @description Modo real: provedor padrao das equipes automaticas e dos juizes sem modelo escolhido.
             * @default neuralake
             */
            real_provider: components["schemas"]["Provider"];
            /**
             * Config Mode
             * @default auto
             * @enum {string}
             */
            config_mode: "auto" | "manual";
            /**
             * Candidate Count
             * @default 2
             */
            candidate_count: number;
            /** Candidates */
            candidates?: components["schemas"]["CandidateConfig-Input"][] | null;
            /** @description Legado: juiz unico. Prefira 'judges'. */
            judge?: components["schemas"]["JudgeConfig-Input"] | null;
            /**
             * Judges
             * @description Painel de juizes; nota final = media ponderada.
             */
            judges?: components["schemas"]["JudgeConfig-Input"][] | null;
            /**
             * Critique Rounds
             * @default 1
             */
            critique_rounds: number;
            /** Seed */
            seed?: number | null;
            /**
             * Mock Scenario
             * @description Somente em modo mock.
             * @default default
             */
            mock_scenario: string;
            /** Tags */
            tags?: string[];
            /** @description Preenchido pelo servidor em POST /runs/{id}/refine. */
            refinement?: components["schemas"]["RefinementSpec-Input"] | null;
            /** @description Preenchido pelo servidor em POST /runs/{id}/action-plan. */
            action_plan?: components["schemas"]["ActionPlanSpec-Input"] | null;
        };
        /**
         * ChallengeConfig
         * @description Configuracao completa de um desafio. Depois de validada e resolvida vira o snapshot imutavel do Run.
         */
        "ChallengeConfig-Output": {
            /** Title */
            title: string | null;
            /** Objective */
            objective: string;
            /**
             * Context
             * @default
             */
            context: string;
            /** Source Ids */
            source_ids: string[];
            /** Constraints */
            constraints: components["schemas"]["Constraint-Output"][];
            rubric: components["schemas"]["Rubric-Output"];
            budget: components["schemas"]["BudgetConfig-Output"];
            /** @default mock */
            mode: components["schemas"]["ExecutionMode"];
            /**
             * @description Modo real: provedor padrao das equipes automaticas e dos juizes sem modelo escolhido.
             * @default neuralake
             */
            real_provider: components["schemas"]["Provider"];
            /**
             * Config Mode
             * @default auto
             * @enum {string}
             */
            config_mode: "auto" | "manual";
            /**
             * Candidate Count
             * @default 2
             */
            candidate_count: number;
            /** Candidates */
            candidates: components["schemas"]["CandidateConfig-Output"][] | null;
            /** @description Legado: juiz unico. Prefira 'judges'. */
            judge: components["schemas"]["JudgeConfig-Output"] | null;
            /**
             * Judges
             * @description Painel de juizes; nota final = media ponderada.
             */
            judges: components["schemas"]["JudgeConfig-Output"][] | null;
            /**
             * Critique Rounds
             * @default 1
             */
            critique_rounds: number;
            /** Seed */
            seed: number | null;
            /**
             * Mock Scenario
             * @description Somente em modo mock.
             * @default default
             */
            mock_scenario: string;
            /** Tags */
            tags: string[];
            /** @description Preenchido pelo servidor em POST /runs/{id}/refine. */
            refinement: components["schemas"]["RefinementSpec-Output"] | null;
            /** @description Preenchido pelo servidor em POST /runs/{id}/action-plan. */
            action_plan: components["schemas"]["ActionPlanSpec-Output"] | null;
        };
        /**
         * CheckResult
         * @enum {string}
         */
        CheckResult: "pass" | "fail" | "unknown";
        /** Constraint */
        "Constraint-Input": {
            /** Constraint Id */
            constraint_id: string;
            /** Description */
            description: string;
            kind: components["schemas"]["ConstraintKind"];
            /**
             * Metric Key
             * @description Metrica que a proposta deve declarar (ex.: monthly_cost_brl).
             */
            metric_key?: string | null;
            /** Limit */
            limit?: number | string | null;
            /** Unit */
            unit?: string | null;
            /**
             * Mandatory
             * @default true
             */
            mandatory: boolean;
        };
        /** Constraint */
        "Constraint-Output": {
            /** Constraint Id */
            constraint_id: string;
            /** Description */
            description: string;
            kind: components["schemas"]["ConstraintKind"];
            /**
             * Metric Key
             * @description Metrica que a proposta deve declarar (ex.: monthly_cost_brl).
             */
            metric_key: string | null;
            /** Limit */
            limit: string | null;
            /** Unit */
            unit: string | null;
            /**
             * Mandatory
             * @default true
             */
            mandatory: boolean;
        };
        /** ConstraintCheck */
        ConstraintCheck: {
            /** Constraint Id */
            constraint_id: string;
            /** Mandatory */
            mandatory: boolean;
            result: components["schemas"]["CheckResult"];
            /** Observed Value */
            observed_value: string | null;
            /** Unit */
            unit: string | null;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Reason */
            reason: string;
        };
        /**
         * ConstraintKind
         * @enum {string}
         */
        ConstraintKind: "numeric_max" | "numeric_min" | "qualitative";
        /** CostBreakdown */
        CostBreakdown: {
            /** Currency */
            currency: string;
            /** Common */
            common: string;
            /** Judge */
            judge: string;
            /** Per Candidate */
            per_candidate: {
                [key: string]: string;
            };
            /** Total */
            total: string;
            /** Pending Unknown Reserved */
            pending_unknown_reserved: string;
            quality: components["schemas"]["CostQuality"];
            /** Calls Used */
            calls_used: number;
            /** Calls Cap */
            calls_cap: number;
            /** Cap */
            cap: string | null;
            /** Strict */
            strict: boolean;
            /**
             * Secondary Calls
             * @description Chamadas feitas no modelo economico, por candidato.
             */
            secondary_calls: {
                [key: string]: number;
            };
            /**
             * Secondary Savings
             * @description Economia estimada vs. fazer as mesmas chamadas no modelo principal (precos versionados).
             */
            secondary_savings: {
                [key: string]: string;
            };
        };
        /**
         * CostQuality
         * @enum {string}
         */
        CostQuality: "provider_reported" | "estimated" | "unknown";
        /** CriterionGrade */
        CriterionGrade: {
            /** Criterion Id */
            criterion_id: string;
            /** Grade */
            grade: string;
            /** Justification */
            justification: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** Critique */
        Critique: {
            /** Objections */
            objections: components["schemas"]["Objection"][];
            /** Strengths */
            strengths: string[];
            /** Author Candidate Id */
            author_candidate_id: string;
            /** Target Candidate Id */
            target_candidate_id: string;
            /** Target Version */
            target_version: number;
            /** Call Ids */
            call_ids: string[];
        };
        /**
         * DecisionStatus
         * @enum {string}
         */
        DecisionStatus: "ranked" | "tie" | "no_eligible_candidate" | "inconclusive" | "not_evaluated";
        /** EfficiencyInfo */
        EfficiencyInfo: {
            /** Cost */
            cost: string | null;
            /** Quota */
            quota: string | null;
            /** Grade */
            grade: string | null;
            cost_quality: components["schemas"]["CostQuality"];
        };
        /**
         * Eligibility
         * @enum {string}
         */
        Eligibility: "eligible" | "ineligible" | "pending";
        /** Evaluation */
        Evaluation: {
            /** Candidate Id */
            candidate_id: string;
            /** Proposal Version */
            proposal_version: number;
            /**
             * Judge Id
             * @default j1
             */
            judge_id: string;
            /**
             * Judge Name
             * @default Padrão
             */
            judge_name: string;
            /** Judge Label */
            judge_label: string;
            /** Rubric Hash */
            rubric_hash: string;
            /** Pack Version */
            pack_version: number;
            /** Grades */
            grades: components["schemas"]["CriterionGrade"][];
            /** Objections */
            objections: string[];
            /** Assumptions */
            assumptions: string[];
            /** Uncertainties */
            uncertainties: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "incomplete";
            /** Call Ids */
            call_ids: string[];
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "mock" | "real";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JudgeConfig
         * @description Um juiz do painel. Sem provider/model_option o servidor usa o padrao do modo; sem rubrica, a do desafio.
         */
        "JudgeConfig-Input": {
            /**
             * Judge Id
             * @description Gerado pelo servidor (j1..jN) se ausente.
             */
            judge_id?: string | null;
            /**
             * Name
             * @default Padrão
             */
            name: string;
            /**
             * Persona
             * @default default
             * @enum {string}
             */
            persona: "default" | "technical" | "business" | "ux" | "custom";
            /**
             * Instructions
             * @description Perspectiva do juiz; entra no prompt de avaliacao.
             * @default
             */
            instructions: string;
            /**
             * Weight
             * @description Influencia do juiz na nota final (relativa).
             * @default 1
             */
            weight: number | string;
            rubric?: components["schemas"]["Rubric-Input"] | null;
            provider?: components["schemas"]["Provider"] | null;
            /** Model Option */
            model_option?: string | null;
            /**
             * Max Output Tokens
             * @default 3000
             */
            max_output_tokens: number;
        };
        /**
         * JudgeConfig
         * @description Um juiz do painel. Sem provider/model_option o servidor usa o padrao do modo; sem rubrica, a do desafio.
         */
        "JudgeConfig-Output": {
            /**
             * Judge Id
             * @description Gerado pelo servidor (j1..jN) se ausente.
             */
            judge_id: string | null;
            /**
             * Name
             * @default Padrão
             */
            name: string;
            /**
             * Persona
             * @default default
             * @enum {string}
             */
            persona: "default" | "technical" | "business" | "ux" | "custom";
            /**
             * Instructions
             * @description Perspectiva do juiz; entra no prompt de avaliacao.
             * @default
             */
            instructions: string;
            /**
             * Weight
             * @description Influencia do juiz na nota final (relativa).
             * @default 1
             */
            weight: string;
            rubric: components["schemas"]["Rubric-Output"] | null;
            provider: components["schemas"]["Provider"] | null;
            /** Model Option */
            model_option: string | null;
            /**
             * Max Output Tokens
             * @default 3000
             */
            max_output_tokens: number;
        };
        /** JudgeScore */
        JudgeScore: {
            /** Judge Id */
            judge_id: string;
            /** Judge Name */
            judge_name: string;
            /** Weight */
            weight: string;
            /** Score 0 100 */
            score_0_100: string | null;
            /** Grades */
            grades: {
                [key: string]: string;
            };
        };
        /** Objection */
        Objection: {
            /** Point */
            point: string;
            /**
             * Severity
             * @default medium
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
            /** Evidence Ids */
            evidence_ids: string[];
            /** Constraint Id */
            constraint_id: string | null;
        };
        /** Proposal */
        Proposal: {
            /** Title */
            title: string;
            /** Recommendation */
            recommendation: string;
            /** Steps */
            steps: string[];
            /** Assumptions */
            assumptions: string[];
            /** Tradeoffs */
            tradeoffs: string[];
            /** Risks */
            risks: string[];
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["ProposalMetric"];
            };
            /** Evidence Ids */
            evidence_ids: string[];
            /** Open Items */
            open_items: string[];
            /** Candidate Id */
            candidate_id: string;
            /** Version */
            version: number;
            /** Invalid Evidence Ids */
            invalid_evidence_ids: string[];
            /**
             * Revised From Critique
             * @default false
             */
            revised_from_critique: boolean;
            /**
             * Revised From Feedback
             * @default false
             */
            revised_from_feedback: boolean;
            /** Call Ids */
            call_ids: string[];
        };
        /** ProposalMetric */
        ProposalMetric: {
            /** Value */
            value: string;
            /** Unit */
            unit: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * Provider
         * @enum {string}
         */
        Provider: "mock" | "neuralake" | "openai" | "gemini" | "anthropic";
        /**
         * RankingEntry
         * @description score_0_100 = media ponderada (pelo peso de cada juiz) das notas dos juizes em judge_scores.
         *     'grades' traz as notas por criterio apenas quando o painel tem um unico juiz (compatibilidade).
         */
        RankingEntry: {
            /** Candidate Id */
            candidate_id: string;
            /** Candidate Name */
            candidate_name: string;
            /** Proposal Version */
            proposal_version: number | null;
            /** Score 0 100 */
            score_0_100: string | null;
            /** Rank */
            rank: number | null;
            /**
             * Co Leader
             * @default false
             */
            co_leader: boolean;
            eligibility: components["schemas"]["Eligibility"];
            /** Grades */
            grades: {
                [key: string]: string;
            };
            /** Judge Scores */
            judge_scores: components["schemas"]["JudgeScore"][];
            efficiency: components["schemas"]["EfficiencyInfo"] | null;
            /** Disqualification Reason */
            disqualification_reason: string | null;
            /** Notes */
            notes: string[];
        };
        /** RefineIn */
        RefineIn: {
            /** Feedback */
            feedback: components["schemas"]["TeamFeedback-Input"][];
            /**
             * General Comment
             * @default
             */
            general_comment: string;
        };
        /**
         * RefinementSpec
         * @description Repescagem pedida pelo cliente: so as equipes listadas seguem na disputa, revisam e sao reavaliadas.
         */
        "RefinementSpec-Input": {
            /** Parent Run Id */
            parent_run_id: string;
            /**
             * Round
             * @default 1
             */
            round: number;
            /** Feedback */
            feedback: components["schemas"]["TeamFeedback-Input"][];
            /**
             * General Comment
             * @default
             */
            general_comment: string;
        };
        /**
         * RefinementSpec
         * @description Repescagem pedida pelo cliente: so as equipes listadas seguem na disputa, revisam e sao reavaliadas.
         */
        "RefinementSpec-Output": {
            /** Parent Run Id */
            parent_run_id: string;
            /**
             * Round
             * @default 1
             */
            round: number;
            /** Feedback */
            feedback: components["schemas"]["TeamFeedback-Output"][];
            /**
             * General Comment
             * @default
             */
            general_comment: string;
        };
        /** Report */
        Report: {
            /** Run Id */
            run_id: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["RunStatus"];
            decision_status: components["schemas"]["DecisionStatus"];
            /** Simulated */
            simulated: boolean;
            /**
             * Replay
             * @default false
             */
            replay: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Winner Candidate Id */
            winner_candidate_id: string | null;
            /** Co Leaders */
            co_leaders: string[];
            /** Decision Reasons */
            decision_reasons: string[];
            /** Ranking */
            ranking: components["schemas"]["RankingEntry"][];
            /** Proposals */
            proposals: components["schemas"]["Proposal"][];
            /** Critiques */
            critiques: components["schemas"]["Critique"][];
            /** Verifications */
            verifications: components["schemas"]["Verification"][];
            /** Evaluations */
            evaluations: components["schemas"]["Evaluation"][];
            /** Evidence Pack Version */
            evidence_pack_version: number | null;
            /** Evidence Gaps */
            evidence_gaps: string[];
            /** Limitations */
            limitations: string[];
            /** Operational Changes */
            operational_changes: string[];
            cost: components["schemas"]["CostBreakdown"];
            /** Next Steps */
            next_steps: string[];
            /** Judge Shuffle Seed */
            judge_shuffle_seed: number | null;
            action_plan: components["schemas"]["ActionPlan"] | null;
            /**
             * Diversity Observed
             * @description provider -> modelos efetivamente informados (ou 'unknown').
             */
            diversity_observed: {
                [key: string]: string[];
            };
        };
        /** Rubric */
        "Rubric-Input": {
            /** Criteria */
            criteria: components["schemas"]["RubricCriterion-Input"][];
            /**
             * Min Score Threshold
             * @description Limiar minimo opcional; default sem limiar universal.
             */
            min_score_threshold?: number | string | null;
        };
        /** Rubric */
        "Rubric-Output": {
            /** Criteria */
            criteria: components["schemas"]["RubricCriterion-Output"][];
            /**
             * Min Score Threshold
             * @description Limiar minimo opcional; default sem limiar universal.
             */
            min_score_threshold: string | null;
        };
        /** RubricCriterion */
        "RubricCriterion-Input": {
            /** Criterion Id */
            criterion_id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Weight */
            weight: number | string;
            /**
             * Computed By
             * @default judge
             * @enum {string}
             */
            computed_by: "judge" | "server_efficiency";
        };
        /** RubricCriterion */
        "RubricCriterion-Output": {
            /** Criterion Id */
            criterion_id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Weight */
            weight: string;
            /**
             * Computed By
             * @default judge
             * @enum {string}
             */
            computed_by: "judge" | "server_efficiency";
        };
        /** RunCreateResponse */
        RunCreateResponse: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Created */
            created: boolean;
            /** Links */
            links: {
                [key: string]: string;
            };
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Owner Id */
            owner_id: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["RunStatus"];
            decision_status: components["schemas"]["DecisionStatus"];
            mode: components["schemas"]["ExecutionMode"];
            /** Simulated */
            simulated: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            /** Seed */
            seed: number;
            /** App Version */
            app_version: string;
            snapshot: components["schemas"]["ChallengeConfig-Output"];
            /** Snapshot Hashes */
            snapshot_hashes: {
                [key: string]: string;
            };
            /** Parent Run Id */
            parent_run_id: string | null;
            /** Error */
            error: string | null;
            metrics: components["schemas"]["RunMetrics"];
            /** Budget Buckets */
            budget_buckets: components["schemas"]["BudgetBucketView"][];
            /**
             * Artifacts
             * @description Artefatos publicos ja produzidos, agrupados por tipo.
             */
            artifacts: {
                [key: string]: unknown;
            };
            /** Last Event Seq */
            last_event_seq: number;
        };
        /** RunEventView */
        RunEventView: {
            /** Seq */
            seq: number;
            /** Type */
            type: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Run Id */
            run_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** RunMetrics */
        RunMetrics: {
            /** Calls Used */
            calls_used: number;
            /** Calls Cap */
            calls_cap: number;
            /** Spent */
            spent: string;
            /** Reserved */
            reserved: string;
            /** Pending Unknown */
            pending_unknown: string;
            /** Cap */
            cap: string | null;
            /** Currency */
            currency: string;
            cost_quality: components["schemas"]["CostQuality"];
            /** Elapsed S */
            elapsed_s: number | null;
            /** Deadline S */
            deadline_s: number;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "partial" | "failed" | "cancelled" | "interrupted";
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["RunStatus"];
            decision_status: components["schemas"]["DecisionStatus"];
            mode: components["schemas"]["ExecutionMode"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Candidate Count */
            candidate_count: number;
            /** Parent Run Id */
            parent_run_id: string | null;
            /** Simulated */
            simulated: boolean;
        };
        /** SourceCreateResponse */
        SourceCreateResponse: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Extraction Status */
            extraction_status: string;
            /** Pages */
            pages: number | null;
            /** Chars */
            chars: number;
            /** Warnings */
            warnings: string[];
        };
        /**
         * SpecialistKind
         * @enum {string}
         */
        SpecialistKind: "document_research" | "calculation";
        /** TeamFeedback */
        "TeamFeedback-Input": {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Comment
             * @description Comentario especifico; pode ficar vazio se houver comentario geral.
             * @default
             */
            comment: string;
        };
        /** TeamFeedback */
        "TeamFeedback-Output": {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Comment
             * @description Comentario especifico; pode ficar vazio se houver comentario geral.
             * @default
             */
            comment: string;
        };
        /** TextSourceIn */
        TextSourceIn: {
            /**
             * Title
             * @default texto colado
             */
            title: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verification */
        Verification: {
            /** Candidate Id */
            candidate_id: string;
            /** Proposal Version */
            proposal_version: number;
            /** Checks */
            checks: components["schemas"]["ConstraintCheck"][];
            /** Valid Evidence Ids */
            valid_evidence_ids: string[];
            /** Invalid Evidence Ids */
            invalid_evidence_ids: string[];
            eligibility: components["schemas"]["Eligibility"];
            /** Reasons */
            reasons: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCreateResponse"][];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_source_api_v1_sources_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_text_source_api_v1_sources_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextSourceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_sources__source_id__get: {
        parameters: {
            query?: {
                preview_chars?: number;
            };
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeConfig-Input"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_detail_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_v1_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_run_api_v1_runs__run_id__refine_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_plan_run_api_v1_runs__run_id__action_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionPlanIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_report_api_v1_runs__run_id__report_get: {
        parameters: {
            query?: {
                format?: "json" | "md";
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                    "text/markdown": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_list_api_v1_runs__run_id__events_list_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_sse_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_prepare_api_v1_demo_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
