"""Contratos Pydantic: fonte unica de JSON Schema/OpenAPI para backend e frontend."""

from app.contracts.artifacts import (  # noqa: F401
    CalcInput,
    CalculationSpec,
    ConstraintCheck,
    CostBreakdown,
    Critique,
    CriterionGrade,
    Derivation,
    Evaluation,
    EvidenceItem,
    EvidenceLocator,
    EvidencePack,
    Finding,
    JudgeOutput,
    Objection,
    PlanValidation,
    Proposal,
    ProposalMetric,
    RankingEntry,
    Report,
    SourceSummary,
    SpecialistTask,
    TaskPlan,
    TaskResult,
    Verification,
)
from app.contracts.challenge import (  # noqa: F401
    BudgetConfig,
    CandidateConfig,
    ChallengeConfig,
    Constraint,
    JudgeConfig,
    Rubric,
    RubricCriterion,
    default_rubric,
)
from app.contracts.common import (  # noqa: F401
    CheckResult,
    ConstraintKind,
    CostQuality,
    DecisionStatus,
    Eligibility,
    EvidenceType,
    ExecutionMode,
    Money,
    Provider,
    Role,
    RunStatus,
    SpecialistKind,
    UsageQuality,
)
from app.contracts.runs import (  # noqa: F401
    BudgetBucketView,
    CallUsageView,
    CatalogResponse,
    RunCreateResponse,
    RunDetail,
    RunEventView,
    RunSummary,
    SourceCreateResponse,
)
